

@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJsYXRpZmYgbnVtb3JvIGR1byIsImVtYWlsIjoibGF0c2xlZnRudXRAZ21haWwuY29tIiwicm9sZSI6IjIiLCJuYmYiOjE3Mzk3OTY4MDcsImV4cCI6MTc0MjM4ODgwNywiaWF0IjoxNzM5Nzk2ODA3fQ.mF1e4__M0NbfwA8HKP3JxkJOxul5p74ha3v0oCo7HYw

GET {{LearningAPI_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

###
# --------------------- user --------------------------------------------------

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "name": "latt",
  "email": "lat@gmail.com",
  "password": "test1234"
}

###

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "name": "betlst",
  "email": "belt@gmail.com",
  "password": "test1234"
}   

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "belt@gmail.com",
  "password": "test1234"
}

###
POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "lat@gmail.com",
  "password": "test1234"
}

###

GET {{LearningAPI_HostAddress}}/user

###

GET {{LearningAPI_HostAddress}}/user?search=bel

###

@id=6
GET {{LearningAPI_HostAddress}}/user/{{id}}
Authorization: Bearer {{token}}

###

PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{

    "name": "",
    "email": "",
    "password": "",
    "gender": "",
    "mobilenumber": "",
    "address": ""
}

###
@id=2
PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{

  "password": "P@ssw0rd123!"
}

###
POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "name": "joseph",
  "email": "josephtay.dzdstm@gmail.com",
  "password": "testpassword1!",
}

###
# @token = 5xyJptLGevHkLvHFAKcjQrKdtf1uoKpcnAu79G-9VL6WQ5khSF-yNiwe3vQCl09h

GET {{LearningAPI_HostAddress}}/user/confirm-email?token={{token}}

###
POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "latiff0601@gmail.com",
  "password": "test12345"
}

###
POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "platiff174@gmail.com",
  "password": "test1234"
}

###
POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "belt@gmail.com",
  "password": "test1234"
}

###
POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "latsleftnut@gmail.com",
  "password": "Test123456789!"
}

###

GET {{LearningAPI_HostAddress}}/user

###

GET {{LearningAPI_HostAddress}}/user?search=bel

###

@id=1
GET {{LearningAPI_HostAddress}}/user/{{id}}
Authorization: Bearer {{token}}
{
    "name": "lattt"
    
}

###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}
# need to fix the bug where after changing name, it doesnt show updated name in the auth
# might be important
###

DELETE {{LearningAPI_HostAddress}}/user/2
Authorization: Bearer {{token}}
###

# ----------------------------     user role    ------------------------------------------
POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  "role": "customer",
  "description": "customer"
}

###
POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  "role": "admin",
  "description": "admin"
}

###

GET {{LearningAPI_HostAddress}}/userrole

###

GET {{LearningAPI_HostAddress}}/userrole/2

###

PUT {{LearningAPI_HostAddress}}/userrole/1
Content-Type: application/json

###

PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "name": "",
    "email": "",
    "password": "",
    "gender": "",
    "mobilenumber": "",
    "address": "",
    "points": "",
    "userRoleId": "",
    "isEmailConfirmed": ""

}

###
PUT {{LearningAPI_HostAddress}}/user/

PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{

  "role": "customer",
  "description": "heheheas"
}

###

DELETE {{LearningAPI_HostAddress}}/userrole/3

###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}
# need to fix the bug where after changing name, it doesnt show updated name in the auth
# might be important
###

DELETE {{LearningAPI_HostAddress}}/user/3
Authorization: Bearer {{token}}
### implement

PUT {{LearningAPI_HostAddress}}/user/password/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password": "test1234",
  "newPassword": "test2345"
}

###

# ----------------------------     user role    ------------------------------------------
POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  "role": "customer",
  "description": "Default role. Customer"
}

###
POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  "role": "admin",
  "description": "admin"
}

###
GET {{LearningAPI_HostAddress}}/userrole

###

GET {{LearningAPI_HostAddress}}/userrole/2

###

PUT {{LearningAPI_HostAddress}}/userrole/1
Content-Type: application/json

{
  "role": "manager",
  "description": "heheheas"
}

###

DELETE {{LearningAPI_HostAddress}}/userrole/1

###

PUT {{LearningAPI_HostAddress}}/user/password/{{id}}
Content-Type: application/json

{
  //UpdateUserPasswordRequest
}

###
# role name cannot be repeated



GET {{LearningAPI_HostAddress}}/user/confirm-email?token={{token}}

{
  "productName": "New Test Product",
  "description": "Test Description",
  "isArchived": false,
  "imageFiles": "shirt.png"
}

###

POST {{LearningAPI_HostAddress}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "productId": 1,
    "quantity": 2,
    "variantId": 1
  },
  {
    "productId": 1,
    "quantity": 1,
    "variantId": 1
  }
]

###


###

DELETE {{LearningAPI_HostAddress}}/cart/2

###

PUT {{LearningAPI_HostAddress}}/cart/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 23,
  "quantity": 6
}

###

GET {{LearningAPI_HostAddress}}/cart/1

###

POST {{LearningAPI_HostAddress}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET {{LearningAPI_HostAddress}}/orders
Authorization: Bearer {{token}}

###





GET {{LearningAPI_HostAddress}}/orders/1
Authorization: Bearer {{token}}

###



GET {{LearningAPI_HostAddress}}/orders/detail/3
Authorization: Bearer {{token}}

###



###


POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  //UserRole
}

###


POST {{LearningAPI_HostAddress}}/feedback
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "rating": 5,
  "feedbackContent": "I LOVE THIS GUN"
  
}

###

###
# ----------------------------     product    ------------------------------------------
# GET {{LearningAPI_HostAddress}}/product/product/13



# POST {{LearningAPI_HostAddress}}/product
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#   "productName": "New Test Product",
#   "description": "Test Description",
#   "isArchived": false,
#   "imageFiles": "shirt.png"
# }



# PUT {{LearningAPI_HostAddress}}/product/1
# Content-Type: application/json

# {
#   "productName": "Updated Test Product",
#   "description": "Updated Test Description",
#   "isArchived": false,
#   "imageFiles": "shirt.png"
# }



# DELETE {{LearningAPI_HostAddress}}/product/1




# POST {{LearningAPI_HostAddress}}/product
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#   "productName": "New Test Product",
#   "description": "Test Description",
#   "isArchived": false,
#   "imageFiles": "shirt.png"
# }


###

POST {{LearningAPI_HostAddress}}/category
Content-Type: application/json

{
  "name": "Bottoms",
  "gender": "Women's"
}

###

POST {{LearningAPI_HostAddress}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productName": "Men's Running T-Shirt",
  "description": "High-performance breathable running t-shirt",
  "imageFile": "tshirt.png",
  "isArchived": false,
  "categoryName": "Tops",
  "categoryGender": "Men's",
  "variants": [
    {
      "color": "Black",
      "size": "M",
      "price": 25.99,
      "stock": 50
    },
    {
      "color": "White",
      "size": "L",
      "price": 25.99,
      "stock": 30
    }
  ]
}

###

GET {{LearningAPI_HostAddress}}/product/product/1

###

PUT {{LearningAPI_HostAddress}}/feedback/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "rating": 5,
  "feedbackContent": "I LOVE THIS APP"
}
###

PUT {{LearningAPI_HostAddress}}/user/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userroleid": 3
}

###

GET {{LearningAPI_HostAddress}}/product/product/0

###


PUT {{LearningAPI_HostAddress}}/user/password/2
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "password": "test1234",
  "newPassword": "P@ssw0rd123!"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "brandonfrancisco512@gmail.com",
  "password": "test1234"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "latiff0601@gmail.com",
  "password": "test12345"
}
PUT {{LearningAPI_HostAddress}}/product/{{id}}
Content-Type: application/json

{
  //UpdateProductRequest
}

###

@productId=0
PUT {{LearningAPI_HostAddress}}/product/update-stock/{{productId}}
Content-Type: application/json

{
  //List
}

###

POST {{LearningAPI_HostAddress}}/userrole
Content-Type: application/json

{
  //UserRole
}

###

GET {{LearningAPI_HostAddress}}/user/confirm-email?token=yssBUTxFpkNdRB-YOUG3gTH2XyMBfaFVfDjyX7FDN2TIJniN2LrVr1lcQ-C08Se0

###

GET {{LearningAPI_HostAddress}}/feedback/all-feedbacks
Authorization: Bearer {{token}}

###

GET {{LearningAPI_HostAddress}}/product/my-products

###
