@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJsYXR0IiwiZW1haWwiOiJsYXRAZ21haWwuY29tIiwibmJmIjoxNzM2OTQ0MjcwLCJleHAiOjE3Mzk1MzYyNzAsImlhdCI6MTczNjk0NDI3MH0.qUEsPrP9SZi-aS_PiqVNaitFyfnFgt4QBKhiS6PcrwE

GET {{LearningAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LearningAPI_HostAddress}}/tutorial?search=hello

###

GET {{LearningAPI_HostAddress}}/tutorial/1

###

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
 "name": "Li Haiyun",
 "email": "li_haiyun@nyp.edu.sg",
 "password": "password123"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
 "email": "li_haiyun@nyp.edu.sg",
 "password": "password123"
}

###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

###
POST {{LearningAPI_HostAddress}}/tutorial
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "Web API",
 "description": "Happy coding :)"
}

###

PUT {{LearningAPI_HostAddress}}/tutorial/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "My Story",
 "description": "Your Song ❤"
}

###

DELETE {{LearningAPI_HostAddress}}/tutorial/2
Authorization: Bearer {{token}}

###


POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "name": "latt",
  "email": "lat@gmail.com",
  "password": "test1234"
}

###

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
  "name": "betlst",
  "email": "belt@gmail.com",
  "password": "test1234"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
  "email": "lat@gmail.com",
  "password": "test1234"
}

###

GET {{LearningAPI_HostAddress}}/user

###

GET {{LearningAPI_HostAddress}}/user?search=bel

###

@id=1
GET {{LearningAPI_HostAddress}}/user/{{id}}
Authorization: Bearer {{token}}

###

PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "name": "",
    "email": "",
    "password": "",
    "gender": "",
    "mobilenumber": "",
    "address": ""
}

###

PUT {{LearningAPI_HostAddress}}/user/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "name": "lattt"
    
}

###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}
###
