@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJMaSBIYWl5dW4iLCJlbWFpbCI6ImxpX2hhaXl1bkBueXAuZWR1LnNnIiwibmJmIjoxNzM2OTU4NzMxLCJleHAiOjE3Mzk1NTA3MzEsImlhdCI6MTczNjk1ODczMX0.EEWQYdNVNsmQJDR9yhz-PaTkhWYBSAw22yRddpLRk9E

GET {{LearningAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LearningAPI_HostAddress}}/tutorial?search=hello

###

GET {{LearningAPI_HostAddress}}/tutorial/1

###

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
 "name": "Li Haiyun",
 "email": "li_haiyun@nyp.edu.sg",
 "password": "password123"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
 "email": "li_haiyun@nyp.edu.sg",
 "password": "password123"
}

###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

###
POST {{LearningAPI_HostAddress}}/tutorial
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "Web API",
 "description": "Happy coding :)"
}

###

PUT {{LearningAPI_HostAddress}}/tutorial/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "My Story",
 "description": "Your Song ❤"
}

###

DELETE {{LearningAPI_HostAddress}}/tutorial/2
Authorization: Bearer {{token}}

###


POST {{LearningAPI_HostAddress}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "productId": 16,
    "quantity": 2,
    "price": 3,
    "productname": "yeap",
    "size": "S"
  }
]

###


###

DELETE {{LearningAPI_HostAddress}}/cart/2

###

PUT {{LearningAPI_HostAddress}}/cart/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 23,
  "quantity": 6
}

###

GET {{LearningAPI_HostAddress}}/cart/1

###

POST {{LearningAPI_HostAddress}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET {{LearningAPI_HostAddress}}/orders
Authorization: Bearer {{token}}

###





GET {{LearningAPI_HostAddress}}/orders/1
Authorization: Bearer {{token}}

###



GET {{LearningAPI_HostAddress}}/orders/detail/3
Authorization: Bearer {{token}}

###

POST {{LearningAPI_HostAddress}}/orders

###

POST {{LearningAPI_HostAddress}}/payment
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "PaymentMethod": "Credit Card",
  "CustomerName": "John Doe",
  "Cvc": "123",
  "Amount": 50.00,
  "CardNo": "4686676683763423"
}

###

GET {{LearningAPI_HostAddress}}/cart/cartitem/37

###
